import { createContext, useContext, useState } from 'react';

const translations = {
  lv: {
    // Navbar
    home: 'Sākums',
    news: 'Ziņas',
    forum: 'Forums',
    materials: 'Materiāli',
    login: 'Pieteikties',
    register: 'Reģistrēties',
    logout: 'Iziet',
    search: 'Meklēt...',
    admin: 'Admin',
    // Home
    heroTitle: 'Astronomijas izglītības platforma',
    heroSubtitle: 'Izpēti Visumu, dalies zināšanās un pievienojies astronomijas entuziastu kopienai Latvijā',
    goToForum: 'Doties uz forumu',
    latestNews: 'Jaunākās ziņas',
    seeAll: 'Skatīt visas →',
    popularPosts: 'Populārākie raksti',
    forumTopics: 'Foruma tēmas',
    noNews: 'Nav ziņu',
    noPosts: 'Nav rakstu',
    // News
    newsTitle: 'Ziņas',
    newsSubtitle: 'Jaunākie notikumi astronomijas pasaulē',
    readMore: 'Lasīt vairāk →',
    noNewsYet: 'Pagaidām nav ziņu',
    backToNews: '← Atpakaļ uz ziņām',
    originalSource: '🔗 Oriģinālais avots',
    // Forum
    forumTitle: 'Forums',
    forumSubtitle: 'Dalies zināšanās ar astronomijas kopienu',
    newPost: '+ Jauns ieraksts',
    allCategories: 'Visas',
    noPostsInCategory: 'Nav ierakstu šajā kategorijā',
    backToForum: '← Atpakaļ uz forumu',
    comments: 'Komentāri',
    addComment: 'Pievienot komentāru',
    commentPlaceholder: 'Rakstiet komentāru... (maks. 500 rakstzīmes)',
    loginToComment: 'lai pievienotu komentāru',
    noCommentsYet: 'Pagaidām nav komentāru. Esi pirmais!',
    delete: 'Dzēst',
    saving: 'Saglabā...',
    // Materials
    materialsTitle: 'Mācību materiāli',
    materialsSubtitle: 'Apgūsti astronomiju un astrofotogrāfiju ar mūsu rokasgrāmatām',
    astronomyTab: 'Astronomija',
    astrophotoTab: 'Astrofotogrāfija',
    allMaterials: 'Visi',
    difficulty: 'Līmenis',
    beginner: 'Iesācējs',
    intermediate: 'Vidējs',
    advanced: 'Pieredzējis',
    noMaterials: 'Nav materiālu šajā kategorijā',
    backToMaterials: '← Atpakaļ uz materiāliem',
    // Auth
    loginTitle: 'Pieteikties',
    loginWelcome: 'Laipni lūdzam atpakaļ!',
    email: 'E-pasta adrese',
    password: 'Parole',
    emailPlaceholder: 'jusu@epasts.lv',
    passwordPlaceholder: 'Ievadiet paroli',
    loggingIn: 'Pieteicos...',
    noAccount: 'Nav konta?',
    forgotPassword: 'Aizmirsi paroli?',
    registerLink: 'Reģistrēties',
    registerTitle: 'Reģistrēties',
    registerWelcome: 'Pievienojies astronomijas kopienai',
    firstName: 'Vārds',
    lastName: 'Uzvārds',
    firstNamePlaceholder: 'Jānis',
    lastNamePlaceholder: 'Bērziņš',
    createPassword: 'Izveidot paroli',
    confirmPassword: 'Apstiprināt paroli',
    minChars: 'Min. 8 simboli',
    repeatPassword: 'Atkārtojiet paroli',
    registering: 'Reģistrējos...',
    hasAccount: 'Jau ir konts?',
    loginLink: 'Pieteikties',
    // Forgot password
    forgotTitle: 'Aizmirsi paroli?',
    forgotSubtitle: 'Ievadi savu e-pastu un nosūtīsim atjaunošanas saiti',
    sendLink: 'Nosūtīt saiti',
    sending: 'Nosūta...',
    backToLogin: '← Atpakaļ uz pieteikšanos',
    // Reset password
    resetTitle: 'Jauna parole',
    resetSubtitle: 'Ievadi savu jauno paroli',
    newPassword: 'Jaunā parole',
    confirmNewPassword: 'Apstiprināt jauno paroli',
    resetButton: 'Atjaunot paroli',
    resetting: 'Atjaunina...',
    // Profile
    profileTitle: 'Mans profils',
    profileSubtitle: 'Pārvaldi sava konta informāciju',
    editProfile: 'Rediģēt profilu',
    saveChanges: 'Saglabāt izmaiņas',
    profileUpdated: 'Profils veiksmīgi atjaunināts',
    roleAdmin: 'Administrators',
    roleUser: 'Lietotājs',
    // Admin
    adminTitle: '⚙ Administrācijas panelis',
    adminSubtitle: 'Pārvaldi lietotājus un satura publicēšanu',
    usersTab: '👥 Lietotāji',
    newsTab: '📡 Publicēt ziņu',
    materialsTab: '📚 Pievienot materiālu',
    publishNews: 'Publicēt jaunu ziņu',
    publishMaterial: 'Pievienot mācību materiālu',
    title: 'Virsraksts',
    content: 'Saturs',
    sourceUrl: 'Avota saite (neobligāts)',
    category: 'Kategorija',
    difficultyLabel: 'Grūtības līmenis',
    publish: 'Publicēt ziņu',
    addMaterial: 'Pievienot materiālu',
    publishing: 'Publicē...',
    published: '✓ Ziņa veiksmīgi publicēta!',
    materialAdded: '✓ Materiāls veiksmīgi pievienots!',
    block: 'Bloķēt',
    unblock: 'Atbloķēt',
    role: 'Loma',
    status: 'Statuss',
    registeredAt: 'Reģistrējās',
    // 404
    notFoundTitle: 'Šī lapa nav atrasta Visumā',
    backHome: 'Atgriezties sākumlapā',
    loading: 'Ielādē...',
    accessDenied: 'Piekļuve liegta',
  },
  en: {
    // Navbar
    home: 'Home',
    news: 'News',
    forum: 'Forum',
    materials: 'Materials',
    login: 'Log In',
    register: 'Register',
    logout: 'Log Out',
    search: 'Search...',
    admin: 'Admin',
    // Home
    heroTitle: 'Astronomy Education Platform',
    heroSubtitle: 'Explore the Universe, share knowledge and join the astronomy community in Latvia',
    goToForum: 'Go to Forum',
    latestNews: 'Latest News',
    seeAll: 'See all →',
    popularPosts: 'Popular Posts',
    forumTopics: 'Forum Topics',
    noNews: 'No news yet',
    noPosts: 'No posts yet',
    // News
    newsTitle: 'News',
    newsSubtitle: 'Latest events in the world of astronomy',
    readMore: 'Read more →',
    noNewsYet: 'No news yet',
    backToNews: '← Back to News',
    originalSource: '🔗 Original Source',
    // Forum
    forumTitle: 'Forum',
    forumSubtitle: 'Share knowledge with the astronomy community',
    newPost: '+ New Post',
    allCategories: 'All',
    noPostsInCategory: 'No posts in this category',
    backToForum: '← Back to Forum',
    comments: 'Comments',
    addComment: 'Add Comment',
    commentPlaceholder: 'Write a comment... (max. 500 characters)',
    loginToComment: 'to add a comment',
    noCommentsYet: 'No comments yet. Be the first!',
    delete: 'Delete',
    saving: 'Saving...',
    // Materials
    materialsTitle: 'Learning Materials',
    materialsSubtitle: 'Learn astronomy and astrophotography with our guides',
    astronomyTab: 'Astronomy',
    astrophotoTab: 'Astrophotography',
    allMaterials: 'All',
    difficulty: 'Level',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    noMaterials: 'No materials in this category',
    backToMaterials: '← Back to Materials',
    // Auth
    loginTitle: 'Log In',
    loginWelcome: 'Welcome back!',
    email: 'Email address',
    password: 'Password',
    emailPlaceholder: 'your@email.com',
    passwordPlaceholder: 'Enter password',
    loggingIn: 'Logging in...',
    noAccount: 'No account?',
    forgotPassword: 'Forgot password?',
    registerLink: 'Register',
    registerTitle: 'Register',
    registerWelcome: 'Join the astronomy community',
    firstName: 'First name',
    lastName: 'Last name',
    firstNamePlaceholder: 'John',
    lastNamePlaceholder: 'Smith',
    createPassword: 'Create password',
    confirmPassword: 'Confirm password',
    minChars: 'Min. 8 characters',
    repeatPassword: 'Repeat password',
    registering: 'Registering...',
    hasAccount: 'Already have an account?',
    loginLink: 'Log In',
    // Forgot password
    forgotTitle: 'Forgot Password?',
    forgotSubtitle: 'Enter your email and we\'ll send a reset link',
    sendLink: 'Send Reset Link',
    sending: 'Sending...',
    backToLogin: '← Back to Login',
    // Reset password
    resetTitle: 'New Password',
    resetSubtitle: 'Enter your new password',
    newPassword: 'New password',
    confirmNewPassword: 'Confirm new password',
    resetButton: 'Reset Password',
    resetting: 'Resetting...',
    // Profile
    profileTitle: 'My Profile',
    profileSubtitle: 'Manage your account information',
    editProfile: 'Edit Profile',
    saveChanges: 'Save Changes',
    profileUpdated: 'Profile updated successfully',
    roleAdmin: 'Administrator',
    roleUser: 'User',
    // Admin
    adminTitle: '⚙ Admin Panel',
    adminSubtitle: 'Manage users and content',
    usersTab: '👥 Users',
    newsTab: '📡 Publish News',
    materialsTab: '📚 Add Material',
    publishNews: 'Publish New Article',
    publishMaterial: 'Add Learning Material',
    title: 'Title',
    content: 'Content',
    sourceUrl: 'Source URL (optional)',
    category: 'Category',
    difficultyLabel: 'Difficulty level',
    publish: 'Publish Article',
    addMaterial: 'Add Material',
    publishing: 'Publishing...',
    published: '✓ Article published successfully!',
    materialAdded: '✓ Material added successfully!',
    block: 'Block',
    unblock: 'Unblock',
    role: 'Role',
    status: 'Status',
    registeredAt: 'Registered',
    // 404
    notFoundTitle: 'This page was not found in the Universe',
    backHome: 'Return to Home',
    loading: 'Loading...',
    accessDenied: 'Access Denied',
  },
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('lang') || 'lv');

  const toggleLang = () => {
    const next = lang === 'lv' ? 'en' : 'lv';
    setLang(next);
    localStorage.setItem('lang', next);
  };

  const t = (key) => translations[lang][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLang = () => useContext(LanguageContext);